### ISSUE TITLE
add `"mad"` method

### ISSUE THREAD

**Issue by timriffe** [timriffe/LifeIneqDecomp#3]
@christiandudel It seems it should work to include the `"mad"` method from `LifeIneq` as one of the options. The only detail is that we'd want a way to pass in the `center_type` argument, which is `"mean"` (`"ex"`) by default, but could also be `"median"`. We don't at this time have a `...` argument in `bw_decomp()`, and we'd need to figure out a nice way to add it to the object `args_i` inside the function. It's doable.

Could you also verify that the following will not fit in the current b-w framework? A checkmark means "correct, that won't work". I include `mad` here, since that's just a hunch on my part.

- [ ] `mad`
- [ ] `H`
- [x] `cov`
- [x] `sd`
- [ ] `aid`

I exclude `cp` and `iqr` because they seem like apparent exclusions. Just to point out, the code runs without error and returns plausible estimates for `H`, `cov` (and even `cp` and `iqr`!), so this exclusion verification is on theoretical grounds.

**Comment by christiandudel** [comment]
Hmm, not 100% sure about this. I will have to think about some of the measures. Will do that next week

**Comment by christiandudel** [comment]
Works: mad, H, aid
Does not work: cov, sd, cp, iqr

The implementation of H and aid requires some changes to the code, and their interpretation is not as nice as for the other measures. Essentially, H can be implemented as e dagger with both W and B divided by e_0, while aid works similar for the Gini coefficient. mad works, but the between-part is a bit weird, as it is a difference-in-difference.

The other measures do not work because they are not as nicely behaved; e.g., cov and sd are nonlinear transformations of the variance. The latter can easily be additively decomposed, its nonlinear transformations cannot.

I will add this to the math-document in the next days, and will implement the methods, should not be much work.

**Comment by christiandudel** [comment]
#4 should solve this more or less, only thing missing is median for mad

**Comment by timriffe** [comment]
excellent, closing this issue and starting a specific minor issue for the case of mad median
